name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]
        xcode: ['14.2']
        include:
          - os: macos-12
            xcode: '14.2'
          - os: macos-12
            xcode: '13.1'
          - os: macos-13
            xcode: '14.3.1'
          - os: macos-14
            xcode: '16_beta_6'
          - os: macos-14
            xcode: '15.4'
          - os: macos-14
            xcode: '14.3.1'
        exclude:
          - os: macos-14
            xcode: '14.2'
    runs-on: ${{ matrix.os }}
    env:
      XC_VERSION: ${{ matrix.xcode }}

    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v4
    - name: Build
      run: "clang++ ./cmp.m -o cmp -ObjC -framework Foundation && ./cmp"
